In [1]:
import pickle

In [2]:
import pandas as pd

In [3]:
walnut_model = pickle.load(open('walnut_lrcv.pkl', 'rb'))

In [4]:
types_df = pd.read_csv('types.csv.bz2', compression='bz2')

In [5]:
types_df.head()

,id,parent_id,scientific_name,scientific_synonyms,taxonomic_rank,en_name,en_synonyms,en_wikipedia_url,de_name,el_name,es_name,fr_name,he_name,it_name,pl_name,pt_br_name,sv_name,category_mask,pending
0,1,285.0,Prunus,NaN,Multispecies,Plum,NaN,http://en.wikipedia.org/wiki/Plum,Pflaume,NaN,NaN,Prunier,NaN,Prugno,NaN,Ameixa,NaN,"forager, honeybee, grafter",False
1,2,843.0,NaN,NaN,NaN,Dumpster (edible),NaN,http://en.wikipedia.org/wiki/Garbage_picking,Müllcontainer,NaN,NaN,Poubelle (comestible),NaN,Cassonetto (commestibili),NaN,NaN,NaN,freegan,False
2,3,263.0,Citrus x sinensis,NaN,Subspecies,Orange,NaN,http://en.wikipedia.org/wiki/Citrus_sinensis,Orange,Πορτοκαλιά,Naranjo dulce,Oranger,תפוז,Arancio dolce,Pomarańcza,Laranja-doce,NaN,"forager, grafter",False
3,4,263.0,Citrus x limon,NaN,Species,Lemon,NaN,http://en.wikipedia.org/wiki/Citrus_limon,Zitrone,Λεμονιά,Limón,Citronnier,לימון,Limone,Cytryna,Limão-siciliano,NaN,"forager, grafter",False
4,5,263.0,Citrus x paradisi,NaN,Subspecies,Grapefruit,NaN,http://en.wikipedia.org/wiki/Citrus_paradisi,Grapefruit,Γκρέιπφρουτ,Pomelo,Pomelo,אשכולית,Pompelmo,Grejpfrut,Toranja,NaN,"forager, grafter",False

In [6]:
types_df['distance_ft'] = 45

In [7]:
types_df.head()

,id,parent_id,scientific_name,scientific_synonyms,taxonomic_rank,en_name,en_synonyms,en_wikipedia_url,de_name,el_name,es_name,fr_name,he_name,it_name,pl_name,pt_br_name,sv_name,category_mask,pending,distance_ft
0,1,285.0,Prunus,NaN,Multispecies,Plum,NaN,http://en.wikipedia.org/wiki/Plum,Pflaume,NaN,NaN,Prunier,NaN,Prugno,NaN,Ameixa,NaN,"forager, honeybee, grafter",False,45
1,2,843.0,NaN,NaN,NaN,Dumpster (edible),NaN,http://en.wikipedia.org/wiki/Garbage_picking,Müllcontainer,NaN,NaN,Poubelle (comestible),NaN,Cassonetto (commestibili),NaN,NaN,NaN,freegan,False,45
2,3,263.0,Citrus x sinensis,NaN,Subspecies,Orange,NaN,http://en.wikipedia.org/wiki/Citrus_sinensis,Orange,Πορτοκαλιά,Naranjo dulce,Oranger,תפוז,Arancio dolce,Pomarańcza,Laranja-doce,NaN,"forager, grafter",False,45
3,4,263.0,Citrus x limon,NaN,Species,Lemon,NaN,http://en.wikipedia.org/wiki/Citrus_limon,Zitrone,Λεμονιά,Limón,Citronnier,לימון,Limone,Cytryna,Limão-siciliano,NaN,"forager, grafter",False,45
4,5,263.0,Citrus x paradisi,NaN,Subspecies,Grapefruit,NaN,http://en.wikipedia.org/wiki/Citrus_paradisi,Grapefruit,Γκρέιπφρουτ,Pomelo,Pomelo,אשכולית,Pompelmo,Grejpfrut,Toranja,NaN,"forager, grafter",False,45

In [8]:
species_df = types_df[['scientific_name', 'distance_ft']]

In [9]:
species_df.head()

     scientific_name  distance_ft
0             Prunus           45
1                NaN           45
2  Citrus x sinensis           45
3     Citrus x limon           45
4  Citrus x paradisi           45

In [10]:
species_df = species_df.dropna()

In [11]:
species_df = species_df.rename(columns={'scientific_name':'s_name'})

In [12]:
walnut_df = species_df

In [15]:
walnut_df['survival'] = walnut_model.predict(walnut_df)

In [16]:
walnut_df.head()

              s_name  distance_ft  survival
0             Prunus           45         0
2  Citrus x sinensis           45         0
3     Citrus x limon           45         0
4  Citrus x paradisi           45         0
5   Persea americana           45         0

In [17]:
pecan_model = pickle.load(open('pecan_lr.pkl', 'rb'))

FileNotFoundError: [Errno 2] No such file or directory: 'pecan_lr.pkl'